### ISSUE TITLE
 NPM won't install libtorrent-node on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by dagnyswaggart** [fanatid/libtorrent-rasterbar#11]
Node version: v6.9.3
Log:

ran with ```npm install --save libtorrent-node```

```
> node-libtorrent@0.0.2 install /home/dagny/code/monorrent/node_modules/node-libtorrent
> node-gyp rebuild

make: Entering directory '/home/dagny/code/monorrent/node_modules/node-libtorrent/build'
  CXX(target) Release/obj.target/libtorrent/src/module.o
../src/module.cpp: In function ‘void nodelt::Initialize(v8::Handle<v8::Object>)’:
../src/module.cpp:41:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("version"),       String::New(LIBTORRENT_VERSION));
                 ^~~~~~
../src/module.cpp:41:53: error: ‘New’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("version"),       String::New(LIBTORRENT_VERSION));
                                                     ^~~~~~
../src/module.cpp:42:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("version_major"), Integer::New(LIBTORRENT_VERSION_MAJOR));
                 ^~~~~~
../src/module.cpp:42:90: error: no matching function for call to ‘v8::Integer::New(int)’
     target->Set(String::NewSymbol("version_major"), Integer::New(LIBTORRENT_VERSION_MAJOR));
                                                                                          ^
In file included from /usr/include/node/node.h:42:0,
                 from ../src/module.cpp:1:
/usr/include/node/v8.h:2558:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^~~
/usr/include/node/v8.h:2558:25: note:   candidate expects 2 arguments, 1 provided
../src/module.cpp:43:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("version_minor"), Integer::New(LIBTORRENT_VERSION_MINOR));
                 ^~~~~~
../src/module.cpp:43:90: error: no matching function for call to ‘v8::Integer::New(int)’
     target->Set(String::NewSymbol("version_minor"), Integer::New(LIBTORRENT_VERSION_MINOR));
                                                                                          ^
In file included from /usr/include/node/node.h:42:0,
                 from ../src/module.cpp:1:
/usr/include/node/v8.h:2558:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^~~
/usr/include/node/v8.h:2558:25: note:   candidate expects 2 arguments, 1 provided
make: *** [libtorrent.target.mk:95: Release/obj.target/libtorrent/src/module.o] Error 1
make: Leaving directory '/home/dagny/code/monorrent/node_modules/node-libtorrent/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.6-1-default
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dagny/code/monorrent/node_modules/node-libtorrent
gyp ERR! node -v v6.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.9.6-1-default
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "node-libtorrent"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-libtorrent@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libtorrent@0.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-libtorrent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-libtorrent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-libtorrent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dagny/code/monorrent/npm-debug.log
```

**Comment by fanatid** [comment]
This repo is not work with new versions of node, you need check feature branch here or use fork with NAN https://github.com/lyssdod/node-libtorrent
