### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by joseym** [fanatid/libtorrent-rasterbar#6]
When trying to install via `npm install node-libtorrent`

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "avenge"
gyp ERR! cwd /Users/joseym/shorts/xbmc/torrent/node_modules/node-libtorrent
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-libtorrent" "--save"
npm ERR! node v0.10.21
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! node-libtorrent@0.0.2 install: `node-gyp avenge`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libtorrent@0.0.2 install script.
npm ERR! This is most likely a problem with the node-libtorrent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp avenge
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libtorrent
npm ERR! There is likely additional logging output above.
```

**Comment by bcomnes** [comment]
Same here:

```
Bret-MBR:test bret$ npm install node-libtorrent-mt

> node-libtorrent-mt@0.0.4 install /Users/bret/Documents/test/node_modules/node-libtorrent-mt
> node-gyp rebuild

  CXX(target) Release/obj.target/libtorrent/src/module.o
../src/module.cpp:4:10: fatal error: 'libtorrent/version.hpp' file not found
#include <libtorrent/version.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/libtorrent/src/module.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bret/Documents/test/node_modules/node-libtorrent-mt
gyp ERR! node -v v0.10.34
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-libtorrent-mt"
npm ERR! node v0.10.34
npm ERR! npm  v2.1.16
npm ERR! code ELIFECYCLE

npm ERR! node-libtorrent-mt@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libtorrent-mt@0.0.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-libtorrent-mt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libtorrent-mt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bret/Documents/test/npm-debug.log
```

**Comment by subodhjena** [comment]
DAMN !! Same here...

```
Subodhs-MacBook-Pro:~ subodhjena$ npm install node-libtorrent

> node-libtorrent@0.0.2 install /Users/subodhjena/node_modules/node-libtorrent
> node-gyp rebuild

  CXX(target) Release/obj.target/libtorrent/src/module.o
../src/module.cpp:4:10: fatal error: 'libtorrent/version.hpp' file not found
#include <libtorrent/version.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/libtorrent/src/module.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/subodhjena/node_modules/node-libtorrent
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/subodhjena/package.json'
npm WARN subodhjena No description
npm WARN subodhjena No repository field.
npm WARN subodhjena No README data
npm WARN subodhjena No license field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-libtorrent"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE

npm ERR! node-libtorrent@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libtorrent@0.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-libtorrent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-libtorrent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-libtorrent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/subodhjena/npm-debug.log
Subodhs-MacBook-Pro:~ subodhjena$ sudo npm install node-libtorrent
Password:

> node-libtorrent@0.0.2 install /Users/subodhjena/node_modules/node-libtorrent
> node-gyp rebuild

  CXX(target) Release/obj.target/libtorrent/src/module.o
../src/module.cpp:4:10: fatal error: 'libtorrent/version.hpp' file not found
#include <libtorrent/version.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/libtorrent/src/module.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/subodhjena/node_modules/node-libtorrent
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/subodhjena/package.json'
npm WARN subodhjena No description
npm WARN subodhjena No repository field.
npm WARN subodhjena No README data
npm WARN subodhjena No license field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-libtorrent"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE

npm ERR! node-libtorrent@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libtorrent@0.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-libtorrent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-libtorrent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-libtorrent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/subodhjena/npm-debug.log
```

**Comment by fanatid** [comment]
@bcomnes @jenasubodh you need install libtorrent dev package (library headers)

**Comment by bcomnes** [comment]
Cool thanks for the tip!

**Comment by RProduction** [comment]
> @bcomnes @jenasubodh you need install libtorrent dev package (library headers)

Hello can you explain it more about libtorrent dev package.
I am trying to install node binding of libtorrent. Seem it fail to build when it tried to search for include header.
Can you give me more insight.

Edit:
I downloaded libtorrent and boost and I add it to node-gyp cache.
It failed to build. It said handle: undeclared identifier.

Edit:
I successfully build libtorrent using instruction on the website. How I use it to build the binding?
